/**
 * Lucide ikonok - globálisan regisztrálva az egész appban
 *
 * Új ikon hozzáadásához:
 * 1. Import hozzáadása fent
 * 2. Hozzáadás a LUCIDE_ICONS_MAP objektumhoz
 * 3. ICONS konstanshoz is add hozzá az icons.constants.ts-ben!
 */
import {
  Home,
  Image,
  Minus,
  ImageDown,
  ShoppingCart,
  Newspaper,
  MessageCircle,
  Settings,
  Bell,
  X,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  LayoutDashboard,
  FolderOpen,
  Folder,
  GraduationCap,
  LogOut,
  QrCode,
  Search,
  School,
  Plus,
  PlusCircle,
  Copy,
  Check,
  Link,
  Unlink,
  RefreshCw,
  Printer,
  Ban,
  // Marketer modul ikonok
  History,
  Phone,
  MapPin,
  Mail,
  Smartphone,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  XCircle,
  Pencil,
  Trash2,
  // Partner modul ikonok
  Users,
  User,
  UserRoundSearch,
  UserCheck,
  UserX,
  UserPlus,
  Calendar,
  Clock,
  Building,
  Building2,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  MinusCircle,
  FolderPlus,
  Expand,
  LayoutTemplate,
  Filter,
  // Státusz ikonok
  Circle,
  FileCheck,
  Camera,
  MailCheck,
  Forward,
  // Photo upload wizard ikonok
  Upload,
  Info,
  Download,
  ExternalLink,
  // Draft picker ikonok
  Play,
  // Step review filter ikonok
  Briefcase,
  // Step choice ikonok (AI vs Manuális párosítás)
  Wand2,
  Hand,
  Sparkles,
  MousePointer2,
  // Lightbox ikonok
  ZoomIn,
  ZoomOut,
  // Partner Orders ikonok
  ShoppingBag,
  Key,
  Grid3x3,
  Frame,
  Sparkle,
  // Client modul ikonok
  Images,
  Save,
  // Lista nézet ikonok
  List,
  FileSpreadsheet,
  // Payment & Billing
  CreditCard,
  Package,
  PackageCheck,
  Wallet,
  Percent,
  // Subscription & Settings
  HardDrive,
  PauseCircle,
  PlayCircle,
  FileText,
  FilePlus,
  Puzzle,
  // Audit log toggle
  Eye,
  // Loading spinner
  Loader2,
  // Biometric / Security
  ScanFace,
  Fingerprint,
  ShieldCheck,
  Lock,
  // Network / Offline
  Wifi,
  WifiOff,
  // Help & Documentation
  HelpCircle,
  BookOpen,
  // Design & Roles
  Palette,
  ClipboardList,
  Megaphone,
  // Bug Reports
  Bug,
  Send,
  Paperclip,
  // QR Code Types
  Pin,
  EyeOff,
  // Deadline countdown
  Hourglass,
  Timer,
  // Monitoring & Export
  Activity,
  Archive,
  // Invoicing
  Receipt,
  Banknote,
  // Webshop
  Store,
  Truck,
  // Tablóméretek
  Ruler,
  // Undo/Redo
  Undo2,
  Redo2,
  // Tags
  Tag,
  // File
  File,
  // More menu
  MoreVertical,
  // Code editor
  Code,
  // Batch automatizálás
  Pause,
  RotateCcw,
  Square,
  ListTodo,
  // Tablókészítő
  Layers,
  // Igazítás
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignStartVertical,
  AlignCenterVertical,
  AlignEndVertical,
  AlignStartHorizontal,
  AlignCenterHorizontal,
  AlignEndHorizontal,
  Rows3,
  Columns3,
  // Rendezés
  ArrowDownAZ,
  ArrowUpDown,
  ListOrdered,
  // Vizuális szerkesztő
  Move,
  AlignHorizontalDistributeCenter,
  AlignVerticalDistributeCenter,
  Maximize2,
  LayoutGrid,
  // Marketplace modulok
  BarChart3,
  Monitor,
  Globe,
  Eraser,
  Crop,
  Bot,
  MessageSquare,
  Vote,
  Contact,
  // Booking Calendar
  CalendarDays,
  CalendarClock,
  CalendarCheck,
  CalendarPlus,
  Clock3,
  Map,
  UsersRound,
  FileDown,
  Repeat,
  Sun,
  Moon,
  // Floating Overlay
  Command,
  Zap,
  SquareStack,
  PanelLeft,
  Type,
  Minimize2,
  GripVertical,
  ChevronsLeftRight,
  MousePointerClick,
  ScanLine,
  Replace,
  FlipHorizontal,
  FlipVertical2,
  Shrink,
  SquareDashedBottom,
  Component,
  Blend,
  LogIn,
  // Email
  ArrowDownLeft,
  ArrowUpRight,
  Reply,
} from 'lucide-angular';

export const LUCIDE_ICONS_MAP = {
  Home,
  Image,
  ImageDown,
  Minus,
  ShoppingCart,
  Newspaper,
  MessageCircle,
  Settings,
  Bell,
  X,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  LayoutDashboard,
  FolderOpen,
  Folder,
  GraduationCap,
  LogOut,
  QrCode,
  Search,
  School,
  Plus,
  PlusCircle,
  Copy,
  Check,
  Link,
  Unlink,
  RefreshCw,
  Printer,
  Ban,
  // Marketer modul ikonok
  History,
  Phone,
  MapPin,
  Mail,
  Smartphone,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  XCircle,
  Pencil,
  Trash2,
  // Partner modul ikonok
  Users,
  User,
  UserRoundSearch,
  UserCheck,
  UserX,
  UserPlus,
  Calendar,
  Clock,
  Building,
  Building2,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  MinusCircle,
  FolderPlus,
  Expand,
  LayoutTemplate,
  Filter,
  // Státusz ikonok
  Circle,
  FileCheck,
  Camera,
  MailCheck,
  Forward,
  // Photo upload wizard ikonok
  Upload,
  Info,
  Download,
  ExternalLink,
  // Draft picker ikonok
  Play,
  // Step review filter ikonok
  Briefcase,
  // Step choice ikonok (AI vs Manuális párosítás)
  Wand2,
  Hand,
  Sparkles,
  MousePointer2,
  // Lightbox ikonok
  ZoomIn,
  ZoomOut,
  // Partner Orders ikonok
  ShoppingBag,
  Key,
  Grid3x3,
  Frame,
  Sparkle,
  // Client modul ikonok
  Images,
  Save,
  // Lista nézet ikonok
  List,
  FileSpreadsheet,
  // Payment & Billing
  CreditCard,
  Package,
  PackageCheck,
  Wallet,
  Percent,
  // Subscription & Settings
  HardDrive,
  PauseCircle,
  PlayCircle,
  FileText,
  FilePlus,
  Puzzle,
  // Audit log toggle
  Eye,
  // Loading spinner
  Loader2,
  // Biometric / Security
  ScanFace,
  Fingerprint,
  ShieldCheck,
  Lock,
  // Network / Offline
  Wifi,
  WifiOff,
  // Help & Documentation
  HelpCircle,
  BookOpen,
  // Design & Roles
  Palette,
  ClipboardList,
  Megaphone,
  // Bug Reports
  Bug,
  Send,
  Paperclip,
  // QR Code Types
  Pin,
  EyeOff,
  // Deadline countdown
  Hourglass,
  Timer,
  // Monitoring & Export
  Activity,
  Archive,
  // Invoicing
  Receipt,
  Banknote,
  // Webshop
  Store,
  Truck,
  // Tablóméretek
  Ruler,
  // Undo/Redo
  Undo2,
  Redo2,
  // Tags
  Tag,
  // File
  File,
  // More menu
  MoreVertical,
  // Code editor
  Code,
  // Batch automatizálás
  Pause,
  RotateCcw,
  Square,
  ListTodo,
  // Tablókészítő
  Layers,
  // Igazítás
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignStartVertical,
  AlignCenterVertical,
  AlignEndVertical,
  AlignStartHorizontal,
  AlignCenterHorizontal,
  AlignEndHorizontal,
  Rows3,
  Columns3,
  // Rendezés
  ArrowDownAZ,
  ArrowUpDown,
  ListOrdered,
  // Vizuális szerkesztő
  Move,
  AlignHorizontalDistributeCenter,
  AlignVerticalDistributeCenter,
  Maximize2,
  LayoutGrid,
  // Marketplace modulok
  BarChart3,
  Monitor,
  Globe,
  Eraser,
  Crop,
  Bot,
  MessageSquare,
  Vote,
  Contact,
  // Booking Calendar
  CalendarDays,
  CalendarClock,
  CalendarCheck,
  CalendarPlus,
  Clock3,
  Map,
  UsersRound,
  FileDown,
  Repeat,
  Sun,
  Moon,
  // Floating Overlay
  Command,
  Zap,
  SquareStack,
  PanelLeft,
  Type,
  Minimize2,
  GripVertical,
  ChevronsLeftRight,
  MousePointerClick,
  ScanLine,
  Replace,
  FlipHorizontal,
  FlipVertical2,
  Shrink,
  SquareDashedBottom,
  Component,
  Blend,
  LogIn,
  // Email
  ArrowDownLeft,
  ArrowUpRight,
  Reply,
};
